# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
# Define a job to be invoked later in a workflow.
jobs:
  say-done:
    # Specify the execution environment.
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    steps:
      - node/install
      - checkout
      - run:
          name: NPM Install
          command: |
            npm install
      - run:
          name: Lint
          command: |
            npm run lint
      - run:
          name: Prettier
          command: |
            npm run prettier
      - run:
          name: Build
          command: |
            npm run build
      - run:
          name: "Done"
          command: "echo Job Done"

# Invoke jobs via workflows
workflows:
  project-workflow:
    jobs:
      - say-done
